### ISSUE TITLE
FAQ怎么运行不了?

### ISSUE THREAD

**Issue by m122469119** [Dawish/MDPlayer#2]
```
java.lang.NoClassDefFoundError: android.transition.Explode
                                                                  at com.danxx.mdplayer.base.BaseActivity.onCreate(BaseActivity.java:25)
                                                                  at android.app.Activity.performCreate(Activity.java:5231)
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2201)
```

**Comment by m122469119** [comment]
FAQ,发一份APk给我把 122469119@qq.com,好人一生平安...
